-- mvp_52~57 (요약본) — 이카운트 API 배관 · 담당자 권한 · 알림 · 주문서 큐 · CRM 세그먼트 · 문의 통합
-- 실제 적용본은 Supabase → Database → Migrations 에 있음. 이 파일은 무엇이 왜 생겼는지 기록용.
--
-- mvp_52_ecount_api ────────────────────────────────────────────────
--   ec.config      회사코드·아이디·인증키·Zone (인증키는 여기서만 산다. 브라우저로 안 나감)
--   ec.api_def     엔드포인트 경로 표 — 문서와 다르면 [옵션·권한] 화면에서 고친다
--   ec.session     SESSION_ID 50분 캐시
--   ec.api_log     호출 기록 (성공/실패·메시지·소요 ms)
--   core.f_ec_login(force)          로그인 → SESSION_ID
--   core.f_ec_call(code, body)      호출 + 로깅 + 세션 만료 시 1회 재시도
--   fn_ec_diag()                    Zone → 로그인 → 재고조회 단계별 진단 (관리자)
--   fn_ec_config() / fn_ec_config_save(jsonb)
--   ※ 호출은 Supabase DB 고정 IP(43.201.156.141)에서 나간다. GitHub Actions 는 IP 가 바뀌어 못 씀.
--
-- mvp_53_perms_and_notify ──────────────────────────────────────────
--   core.perm_def   store 화면 메뉴 단위 권한 11종
--   core.staff_perm 담당자 × 권한 (행이 없고 perm_set=false 면 default_on 묶음을 씀)
--   core.f_staff_perms(name) / core.f_has_perm(name, perm)
--   fn_staff_perms() / fn_staff_perm_save(id, perms[], use_default) / fn_staff_save(jsonb)
--   core.notify_channel / core.notify_rule / core.notify_log
--   core.f_notify(event, vars)      규칙에 걸린 채널로 발송 + 로깅
--   fn_notify_config() / fn_notify_save(jsonb) / fn_notify_test(rule)
--
-- mvp_54_order_queue ───────────────────────────────────────────────
--   ec.order_queue / ec.order_queue_line
--   core.f_order_submit(data, by)   전 줄 검증 → 재고 부족이면 등록 안 함(shortage 반환)
--                                   → 통과하면 큐 적재 + 라인마다 inv.movement(out) 기록
--   fn_order_submit(jsonb)          관리자·직원 계정
--   fn_store_order_submit(code, jsonb)  담당자 PIN (perm='order' 필요)
--   fn_order_queue(...) / fn_order_send(ids[]) / fn_order_void(id, reason)
--   ※ 취소는 전송 전에만 가능하고, 빠졌던 재고를 in 으로 되돌린다.
--
-- mvp_55_crm_segment ───────────────────────────────────────────────
--   crm.segment                     조건 묶음을 이름 붙여 저장 (기본 6종)
--   fn_crm_segments() / fn_crm_segment_save(jsonb) / fn_crm_segment_delete(code)
--   fn_crm_segment_run(code, reason, ...)  last_days_min/max(오늘 기준 상대 기간)를
--                                          절대 날짜로 바꿔 fn_crm_targets_v2 를 호출
--   fn_crm_pool()                   모수 깔때기 (전체→동의→번호→구매이력 연결)
--   [버그 수정] fn_crm_targets_v2 의 by_category 집계가 'group by 1' 로 집계함수를
--              GROUP BY 에 넣어 함수 전체가 실패하고 있었다 → group by 표현식으로 교정
--
-- mvp_56_inquiry_unified ───────────────────────────────────────────
--   crm.v_inquiry                   견적(quote) + 구독·매장(submission) + 소모품/VMS(consult) 통합 뷰
--   fn_inquiry_list(form, status, q, from, to, limit, offset, unmask)
--
-- mvp_57_store_perm_guards ─────────────────────────────────────────
--   fn_store_orders(code, limit)    담당자 화면 최근 주문서 (perm='order')
--   fn_stock_search / fn_stock_move 에 perm='stock' / 'stock_move' 검사 추가
--   fn_store_status 에 perms·dept 추가 → /store 가 메뉴를 스스로 감춘다

-- mvp_58_ecount_sync ──────────────────────────────────────────────
--   ec.sync_log                     가져오기 이력
--   core.f_ec_product_sync(by)      품목 조회 → inv.item upsert (2,433건 확인)
--   core.f_ec_stock_sync(whs[], by) 창고별 재고현황 → inv.movement kind='sync' (차이만, 멱등)
--                                   · 이카운트에 없는 품목은 자동 생성
--                                   · 이카운트에 잔고 없는데 우리 원장에 남은 건 0 으로 정리
--                                   · 창고 하나가 실패하면 즉시 중단 (오류를 12건 쌓지 않기 위해)
--   core.f_ec_customer_sync(by)     거래처 조회 → ec.customer
--   fn_ec_sync(what, whs[]) / fn_ec_sync_log(limit)
--
-- mvp_58b/c ────────────────────────────────────────────────────────
--   [발견] 이카운트 세션이 죽으면 JSON 이 아니라 IIS 412 HTML 이 온다 → 세션 만료로 판정해 재로그인
--   [발견] 로그인 성공 코드는 Data.Code = '00' 이다 ('000' 만 보고 있어 항상 실패로 기록됐다)
--   [발견] 세션 유효시간이 짧다 → 캐시를 50분에서 10분으로 줄임
--   응답의 QUANTITY_INFO(일일 허용량)를 ec.api_log.quota 에 저장
--
-- mvp_59_ec_circuit_breaker ────────────────────────────────────────
--   이카운트 제한 : **시간당 연속 오류 30건 / 1일 5,000건**. 넘기면 계정이 시간 단위로 막힌다.
--   core.f_ec_guard()               마지막 성공 이후 연속 실패가 ec.config.max_fail(기본 8) 이상이면
--                                   30분 자동 정지 + 이후 호출 거부 (errcode 55006)
--   ec.config.paused_until          정지 해제 시각 · fn_ec_resume() 으로 관리자가 수동 해제
--   재로그인 쿨다운 60초 · 재시도는 호출당 1회

-- mvp_60_inquiry_edit_flags ───────────────────────────────────────
--   crm.inquiry_flag(form, src_id, is_test, hidden, note)  원본 3개 테이블을 건드리지 않는 오버레이
--   core.f_looks_test(name, phone, text, handler)          테스트 자동 판별
--       · 이름/내용에 test·테스트·더미 · 홍길동/이순신/김철수 같은 더미 이름
--       · **고객명이 우리 직원 이름이면 본인 테스트로 본다** (지용현·차효범 등)
--       · 알려진 테스트 번호, 010XXXX 반복 패턴, 10자리 미만 번호
--   crm.v_inquiry 확장 : web_subscription(구독문의) 추가 · 견적은 **최신 버전만** · auto_test 컬럼
--   fn_inquiry_list(..., p_show)  real(기본) | test | hidden | all  + counts
--   fn_inquiry_flag(form, ids[], is_test, hidden, note)
--   fn_inquiry_save(form, id, data)   원본 테이블에 이름·연락처·담당·상태·내용 반영
--   fn_inquiry_delete(form, ids[], hard)  기본은 숨김(되돌리기 가능) · hard=true 는 관리자만
--
-- mvp_61_quote_number_parse ───────────────────────────────────────
--   [버그] 견적 GAS 가 시트 셀 값을 그대로 보내는데 "6,019,200" 처럼 **콤마가 든 문자열**이라
--          fn_submit_quote 의 ::numeric 캐스팅이 터졌다. GAS 는 muteHttpExceptions 로 삼켜서
--          "시트에는 쌓이는데 현행 시스템에는 안 들어오는" 상태가 계속됐다.
--   core.f_num(text) / core.f_int(text) 로 숫자만 뽑아 캐스팅하도록 교체.
--
-- 시트 백필 (2026-09-05) ──────────────────────────────────────────
--   견적내역        19건(견적번호 8개, 버전 포함)  → crm.quote
--   구독문의 상담관리 45건                          → crm.consult(web_subscription)
--   소모품·렌탈      2건 (테스트 4건은 함수가 자동 제외) → crm.consult(web_supply)
--   VMS·B2B         2건 (테스트 1건 자동 제외)       → crm.consult(web_b2b)
--   결과 : 실제 48건 / 테스트 12건

-- mvp_62_inquiry_columns ──────────────────────────────────────────
--   문의 목록이 "목적: X / 지역: Y / 메모" 한 덩어리라 읽기 어려웠다.
--   crm.v_inquiry 를 다시 만들어 kind(관심·상품) · purpose(목적) · region(지역) · memo 로 분리.
--   구독문의는 consult.content 에서 regexp 로 "목적:" "지역:" 을 뽑아내고 나머지를 메모로.
--   견적은 purpose 자리에 최종가·월구독료·버전을 넣는다.
--   fn_inquiry_list 기본 페이지 크기 50 → 25, 응답에 limit 포함.

-- mvp_63_dash_warm_presets ────────────────────────────────────────
--   [발견] 대시보드 캐시(core.dash_cache)는 정상 동작하나(예열 시 1~9ms, 미예열 1.5초)
--          fn_dash_refresh 가 "N개월 전 1일~오늘" 한 칸만 만들어서
--          화면 기본값인 **30일** 은 늘 캐시 미스였다.
--   화면이 실제로 쓰는 기간 버튼 6종 × 모드 2종 = 12칸을 미리 만들도록 교체.
--   샵링커 수집(collect.mjs)이 주문을 넣으면 캐시가 비워지므로,
--   수집 끝에서 fn_dash_refresh 를 불러 다시 예열한다.

-- mvp_64_pg_cron_jobs ─────────────────────────────────────────────
--   [발견] GitHub 예약 실행이 3~4.5시간씩 밀린다 (13:10 KST 슬롯 → 실제 17:48,
--          23:10 슬롯 → 실제 02:18/02:34). 그래서 Supabase pg_cron(설치돼 있음)으로 옮김.
--   core.f_dash_warm()  대시보드 캐시 12칸 예열
--   cron 'dash-warm'         매시 25분
--   cron 'ecount-stock-sync' 매일 03:00 KST — 창고별 재고현황 → kind='sync'
--   cron 'ecount-unpause'    15분마다 — 차단기 자동 해제
--   fn_cron_status(limit)    화면에서 실행 이력 확인
--
-- mvp_65_sl_order_pull ────────────────────────────────────────────
--   자동 수집된 샵링커 주문을 골라 주문서로 만드는 경로 (수기 입력 대체)
--   core.f_ec_code_of(name, model)  상품명/모델 → 이카운트 품목코드 4단계 매칭
--       ① 상품명 전체가 별칭과 일치 ② 모델코드가 별칭과 일치
--       ③ 모델코드가 품목 코드/모델과 일치 ④ 상품명 안에 별칭이 포함(긴 것 우선)
--       → 최근 3일 239건 중 201건(84%) 자동 매칭 확인
--   core.f_sl_pending(days,q,channel,limit)  아직 주문서로 안 만든 샵링커 주문 (주문번호 단위)
--   core.f_sl_to_order(order_nos[], wh, by)  골라서 큐 생성 + 재고 차감 (미매칭·재고부족은 건너뛰고 사유 반환)
--   fn_sl_pending / fn_sl_to_order          관리자
--   fn_store_sl_pending / fn_store_sl_to_order  담당자 PIN (perm='order')
--   fn_alias_add(alias, code)               못 찾은 상품명을 화면에서 바로 코드에 연결

-- mvp_66_menu_manager ─────────────────────────────────────────────
--   관리자 메뉴(왼쪽 네비)를 DB에서 관리한다. /admin → 옵션·권한 → "관리자 메뉴"
--   core.menu_group(code,label,sort,state,note)   6그룹 : _top/sales/crm/inv/data/ops
--   core.menu_item (code,group_code,label,sort,state,note)  18메뉴
--   state : 'on' 정상 · 'dev' 메뉴엔 보이되 누르면 공사 중 안내 · 'off' 메뉴에서 숨김
--   fn_menu()        로그인한 사람이 볼 메뉴 (off 제외) — admin.html 이 부팅 때 호출
--   fn_menu_admin()  관리자 편집용 (off 포함, sort/note 포함)
--   fn_menu_save(jsonb {groups:[],items:[]})  라벨·순서·상태·안내문구 일괄 저장
--   화면쪽: NAV_ICON(코드→아이콘), NAV_FALLBACK(DB를 못 읽어도 뜨는 기본 구성),
--          renderNav() / renderUnderConstruction() / #v-dev (공사 중 화면)
--
-- (화면) RPC 45초 캐시 ─────────────────────────────────────────────
--   admin.html 의 rpc() 가 조회 계열 결과를 45초 담아둔다. 저장 계열
--   (save/_set/delete/submit/sync/… )은 담지 않고, 실행되면 캐시를 통째로 비운다.
--   화면을 왔다갔다 할 때 같은 질의가 다시 나가지 않아 체감 속도가 붙는다.

-- mvp_67_dev_gate_menu ────────────────────────────────────────────
--   "메뉴를 보이게 할지 말지"는 개발자만 만진다.
--   개발자 계정  yonghyeon@samsungat.local (로그인 아이디 `yonghyeon`) · role=admin
--   core.app_setting['dev_users'] = 쉼표로 구분한 이메일 목록. 비우면 admin 전원 허용
--   core.f_is_dev()  admin 이면서 dev_users 에 든 계정만 true
--   fn_me() 에 is_dev 추가 → 화면이 [관리자 메뉴] 카드를 보일지 정한다
--   fn_menu_admin / fn_menu_save 는 f_is_dev() 로 잠금 (일반 admin 은 카드도 안 보이고 호출도 막힘)
--   화면: 3단 세그먼트 → **토글(메뉴에 보이기) + 라디오(공개 / 개발 중)**.
--         토글을 껐다 켜면 끄기 직전 상태로 돌아온다(o._prev). 그룹은 토글만.
--
--   [경로] 메뉴 관리는 관리자 화면 안이 아니라 **/admin/option** 독립 페이지.
--          web/admin/option/index.html (자체 로그인 · 미리보기 패널 포함)
--          web/admin/index.html 은 ../admin.html 로 보내는 리다이렉트 (경로 충돌 방지)
--          admin.html 의 [옵션·권한] 에는 링크 배너만 남고, 개발자 계정에만 보인다
--
-- (수정) 넓은 화면 정렬 ─────────────────────────────────────────
--   헤더는 폭 제한이 없고 본문(.view)만 1720~1840px 로 묶여 있어서, 2560px 같은
--   넓은 화면에서 헤더 오른쪽 표시(데이터 기준·최근 적재)가 카드보다 200px 쯤 더
--   오른쪽에 있었다. --maxw 변수 하나로 묶고 header/.content 에 같은
--   padding: max(28px, (100% - var(--maxw))/2) 를 줘서 좌우가 정확히 맞는다.
--   폭 상한도 화면에 따라 1720 / 1900 / 2100 / 2300px 로 단계를 늘렸다.
--
-- (수정) 개발자 계정 로그인 실패 ─────────────────────────────────
--   auth.users 를 SQL 로 직접 만들면 confirmation_token 등 토큰 칼럼이 NULL 이라
--   GoTrue 가 "Database error querying schema" 로 로그인을 거부한다.
--   해당 칼럼들을 '' 로 채워야 한다(정상 계정은 전부 빈 문자열).

-- mvp_68~70 : 옵션 모델 · 품목 후보 · 주문서 미리보기 ─────────────
--  [고침] fn_customer_list 가 STABLE 인데 실명보기 감사로그를 insert 해서
--         "INSERT is not allowed in a non-volatile function" 로 죽었다 → VOLATILE.
--
--  [옵션명이 진짜 모델명]  오픈마켓은 상품 하나에 서로 다른 모델을 옵션으로 붙여 판다.
--    예) 상품명 "천장형 에어컨 냉방 리모컨 AR-EC05" · 옵션 "AR-EH05(냉난방전용)"
--        → 실제 판매품은 AR-EH05. 상품명으로 매칭하면 다른 물건이 나간다.
--    core.f_model_in_option(option)  옵션 문자열에서 모델처럼 생긴 토막을 뽑는다
--        (5~24자 · 영문 포함 · 하이픈 또는 숫자 포함 · 순수 숫자 아님,
--         이카운트 품목으로 실제 풀리는 것 우선, 그다음 긴 것)
--    core.f_sl_model(model, option)  화면에 보여줄 "실제 모델"
--    최근 30일 2,833줄 중 108줄의 매칭이 바뀌었다 (AR-EC05→AR-EH05,
--    WD90F25CHW→WD90H25BHW, SM-R420NZAAKOO→SM-R420NZKAKOO 등 전부 교정)
--
--  [후보를 사람이 고른다]  같은 모델에 품목이 여러 개인 경우가 많다
--    (MLT-D111S → /TND · 1+1 · (재생) / CLT-K403S → 4색 패키지 · 1+1 · /TND).
--    자동으로 하나를 고르면 엉뚱한 게 나가므로 **후보를 다 주고 사람이 고른다**.
--    core.f_ec_cands(name, model, option) → [{code,name}] 순위:
--      ①옵션모델→별칭 ②옵션모델→품목 ③상품명전체→별칭 ④모델코드→별칭
--      ⑤모델코드→품목 ⑥상품명에 별칭 포함
--    최근 30일 기준 2,573줄 매칭 / 554줄은 후보 여럿(선택 필요) / 260줄 미매칭
--
--  [주문서 미리보기]  주문 1건 = 전표 1장. 만들기 전에 그대로 보여준다.
--    core.f_sl_preview(order_nos[], wh, picks) / fn_sl_preview · fn_store_sl_preview
--    picks = {"주문번호#줄번호":"품목코드"} — 고른 값은 f_sl_to_order 까지 그대로 간다
--    미리보기에 거래처·출하창고·특이사항·합계와 줄별 재고를 같이 보여주고,
--    품목 미정·선택 필요가 남아 있으면 [이대로 만들기] 를 막는다
--
--  (화면) 눌렀다는 게 보이게 : 상단 진행 바(#loadbar, rpc 진행 카운터),
--    버튼 눌림 애니메이션, "새로고침/조회" 버튼은 스피너 + 끝나면 완료 토스트.
--    모바일에서 .card h3 가 flex-nowrap 이라 설명 문구가 세로 한 줄로 눌리던 것도 고침.

-- mvp_71 : 자동 선택은 기존 맵핑으로 되돌림 ────────────────────────
--   f_ec_cands 의 **첫 번째 후보 = 기존 f_ec_code_of(상품명, 모델코드) 결과와 동일**.
--   옵션에서 뽑은 모델은 자동 적용하지 않고 후보 목록 뒤쪽에 opt=true 로만 붙는다.
--   후보 순위 ①상품명전체→별칭 ②모델코드→별칭 ③모델코드→품목 ④상품명에 별칭 포함
--              ⑤옵션모델→별칭 ⑥옵션모델→품목  (⑤⑥은 참고용)
--   최근 30일 2,780줄 기준 : 기존과 동일 2,466 / 새로 잡힘 53 / 옵션 대안 있음 121
--   남은 차이 12줄은 ec.product_alias 가 inv.item 에 없는 코드를 가리키던 것
--   (예: 'WD-FLTR', 'AT00609') — 주문서를 만들 때 어차피 "없는 품목" 으로 실패했을 건들.
--
-- (고침) 주문서·전송 화면이 비어 보이던 것 ────────────────────────
--   네비를 DB로 그리면서 주문서 메뉴의 뱃지(#badgeOq)가 없어졌는데 loadOq 가 그 요소를
--   붙잡다가 TypeError 로 죽어 표·건수·빈 안내가 모두 안 그려졌다. null 확인 + NAV_BADGE 등록.
--   빈 표에는 "아직 만든 주문서가 없다 · 샵링커 대기 N건" 안내와 바로가기 버튼을 둔다.

-- mvp_72 : 샵링커 가져오기 "statement timeout" ──────────────────────
--   [원인] 후보 목록(f_ec_cands)을 붙이면서 한 번 열 때 39초가 걸려 API 8초 제한에 걸렸다.
--     ① f_model_in_option 이 옵션 토큰마다 f_ec_code_of(4단계 조회)를 다시 돌림
--     ② f_sl_pending 의 CTE 가 인라인되어 f_ec_cands 가 줄마다 5~6번 평가됨
--     ③ 같은 (상품명·모델·옵션) 조합이 수백 번 반복되는데 매번 새로 계산
--     (어제까지 돌던 옛 함수도 4.5초쯤 걸려 제한 턱밑이었다)
--   [대책] 토큰 확인은 정확일치만 · 조합을 distinct 로 뽑아 한 번씩만 계산 ·
--          조합별 캐시 ec.cand_cache(별칭·품목이 바뀌면 트리거로 비움, 1일 TTL) ·
--          매시 예열(f_dash_warm)에 f_sl_pending(30일)을 넣어 늘 따뜻하게
--   [결과] 39초 → 처음 3.4초 → 캐시 후 0.9초. 7일 대기 590건 기준.

-- mvp_73 : 실수했을 때 되돌리기 ──────────────────────────────────
--   재고는 "지우는" 게 아니라 **반대 이동을 한 줄 더 쌓아** 되돌린다(inv.movement kind='in',
--   ref_type='order_void'). 그래서 언제 누가 무엇을 되돌렸는지 이력이 남는다.
--   ec.order_queue.batch_id  한 번에 만든 묶음 표시 'SL-YYMMDD-HHMISS-담당'
--   fn_order_void(id)                 한 건 취소 (기존)
--   fn_order_void_many(ids[])         여러 건
--   fn_order_void_batch(batch_id)     묶음 통째로 — sent(이카운트 전송됨)는 건너뜀
--   fn_order_batches(hours)           최근 72시간 묶음 목록 (화면 위쪽 "최근 만든 묶음")
--   화면 : 만들기 직후 결과 창에 [방금 만든 N건 되돌리기] · 주문서 페이지 위쪽 묶음 띠에
--          [되돌리기 N] · 둘 다 "되돌리기" 를 타이핑해야 눌린다. Esc/바깥 클릭으로는 안 됨.

-- mvp_74 : 단계별 주문 변환 (코드아이식 4단계) ──────────────────────
--   기존 빠른 모드(샵링커 주문 가져오기 모달)는 그대로 두고, 두 번째 모드를 붙였다.
--   ① 데이터 불러오기 (기간·날짜기준·채널·검색 · 이미 만든 것 포함 여부)
--   ② 데이터 선택   (주문 단위 체크 · 바로 가능/확인 필요/코드 없음/이미 만듦 필터)
--   ③ 코드 매핑     (같은 상품·옵션을 한 줄로 묶어 한 번에 지정 · 후보 select · 검색 · "기억"=별칭 저장)
--   ④ 변환 결과     (전표 미리보기 → 저장(재고 차감) · 관리자는 "저장 후 바로 이카운트 전송")
--   진행 상태는 브라우저에 저장 → 다시 열면 "작업을 이어서 진행할까요?" (코드아이와 같음)
--   관리자 admin.html : 왼쪽 메뉴 [주문 변환] (menu_item 'wiz', 재고 그룹) · 주문서 페이지 "단계별로 하기 →"
--   담당자 store.html : 주문서 탭 위 [빠른 모드 | 단계별 모드] 토글, 기본은 단계별
--   공용 코드 web/_wiz/wiz.js · wiz.css (마커 WIZ:*:BEGIN/END 로 두 파일에 인라인)
--   API : fn_sl_orders / fn_store_sl_orders (core.f_sl_range — 기간·기준일·완료포함)
--         fn_store_items · fn_store_alias_add · fn_store_warehouses (담당자용)
--   참고 : 코드아이 변환 결과(2026-09-04 18:05, 61줄)를 보니 고창재 프로가 AR-EC05 상품의
--          옵션 AR-EH05 건을 손으로 AT-00624 로 고쳐 넣었음 — 3단계 "옵션엔 AR-EH05" 표시가 그 자리.

-- mvp_75 : 담당자도 이카운트 전송 ────────────────────────────────
--   권한 'send'(이카운트 전송) 신설 — 관리자가 [옵션·권한]에서 사람별로 켜고 끈다.
--   지금 '주문서 등록(order)' 이 있던 박은지·고창재·지용현에게는 자동으로 켜 줌.
--   core.f_order_send(ids, by) 로 전송 본체를 공용화, 건별 결과(detail) 반환.
--   fn_order_send(관리자) · fn_store_order_send(p_code, ids)(담당자, perm='send')
--   fn_store_orders 에 can_send · pending_ids · slip · msg 추가.
--   화면 : 공용 확인창 ecSend() — "실제 전표가 생긴다 / 여기서 되돌릴 수 없다 / 실패는 대기로 남는다"
--          세 줄 + 확인 체크 후에만 버튼 활성, 전송 중 닫힘 방지, 끝나면 건별 결과표(전표번호·사유).
--          담당자 빠른 모드: "전송 대기 N건" 띠 + 행별 [전송] · 단계별 모드: 저장 뒤 [이카운트로 전송 (N장)]
--          관리자 주문서 페이지의 전송도 같은 창으로 통일.
