-- mvp_52~57 (요약본) — 이카운트 API 배관 · 담당자 권한 · 알림 · 주문서 큐 · CRM 세그먼트 · 문의 통합
-- 실제 적용본은 Supabase → Database → Migrations 에 있음. 이 파일은 무엇이 왜 생겼는지 기록용.
--
-- mvp_52_ecount_api ────────────────────────────────────────────────
--   ec.config      회사코드·아이디·인증키·Zone (인증키는 여기서만 산다. 브라우저로 안 나감)
--   ec.api_def     엔드포인트 경로 표 — 문서와 다르면 [옵션·권한] 화면에서 고친다
--   ec.session     SESSION_ID 50분 캐시
--   ec.api_log     호출 기록 (성공/실패·메시지·소요 ms)
--   core.f_ec_login(force)          로그인 → SESSION_ID
--   core.f_ec_call(code, body)      호출 + 로깅 + 세션 만료 시 1회 재시도
--   fn_ec_diag()                    Zone → 로그인 → 재고조회 단계별 진단 (관리자)
--   fn_ec_config() / fn_ec_config_save(jsonb)
--   ※ 호출은 Supabase DB 고정 IP(43.201.156.141)에서 나간다. GitHub Actions 는 IP 가 바뀌어 못 씀.
--
-- mvp_53_perms_and_notify ──────────────────────────────────────────
--   core.perm_def   store 화면 메뉴 단위 권한 11종
--   core.staff_perm 담당자 × 권한 (행이 없고 perm_set=false 면 default_on 묶음을 씀)
--   core.f_staff_perms(name) / core.f_has_perm(name, perm)
--   fn_staff_perms() / fn_staff_perm_save(id, perms[], use_default) / fn_staff_save(jsonb)
--   core.notify_channel / core.notify_rule / core.notify_log
--   core.f_notify(event, vars)      규칙에 걸린 채널로 발송 + 로깅
--   fn_notify_config() / fn_notify_save(jsonb) / fn_notify_test(rule)
--
-- mvp_54_order_queue ───────────────────────────────────────────────
--   ec.order_queue / ec.order_queue_line
--   core.f_order_submit(data, by)   전 줄 검증 → 재고 부족이면 등록 안 함(shortage 반환)
--                                   → 통과하면 큐 적재 + 라인마다 inv.movement(out) 기록
--   fn_order_submit(jsonb)          관리자·직원 계정
--   fn_store_order_submit(code, jsonb)  담당자 PIN (perm='order' 필요)
--   fn_order_queue(...) / fn_order_send(ids[]) / fn_order_void(id, reason)
--   ※ 취소는 전송 전에만 가능하고, 빠졌던 재고를 in 으로 되돌린다.
--
-- mvp_55_crm_segment ───────────────────────────────────────────────
--   crm.segment                     조건 묶음을 이름 붙여 저장 (기본 6종)
--   fn_crm_segments() / fn_crm_segment_save(jsonb) / fn_crm_segment_delete(code)
--   fn_crm_segment_run(code, reason, ...)  last_days_min/max(오늘 기준 상대 기간)를
--                                          절대 날짜로 바꿔 fn_crm_targets_v2 를 호출
--   fn_crm_pool()                   모수 깔때기 (전체→동의→번호→구매이력 연결)
--   [버그 수정] fn_crm_targets_v2 의 by_category 집계가 'group by 1' 로 집계함수를
--              GROUP BY 에 넣어 함수 전체가 실패하고 있었다 → group by 표현식으로 교정
--
-- mvp_56_inquiry_unified ───────────────────────────────────────────
--   crm.v_inquiry                   견적(quote) + 구독·매장(submission) + 소모품/VMS(consult) 통합 뷰
--   fn_inquiry_list(form, status, q, from, to, limit, offset, unmask)
--
-- mvp_57_store_perm_guards ─────────────────────────────────────────
--   fn_store_orders(code, limit)    담당자 화면 최근 주문서 (perm='order')
--   fn_stock_search / fn_stock_move 에 perm='stock' / 'stock_move' 검사 추가
--   fn_store_status 에 perms·dept 추가 → /store 가 메뉴를 스스로 감춘다

-- mvp_58_ecount_sync ──────────────────────────────────────────────
--   ec.sync_log                     가져오기 이력
--   core.f_ec_product_sync(by)      품목 조회 → inv.item upsert (2,433건 확인)
--   core.f_ec_stock_sync(whs[], by) 창고별 재고현황 → inv.movement kind='sync' (차이만, 멱등)
--                                   · 이카운트에 없는 품목은 자동 생성
--                                   · 이카운트에 잔고 없는데 우리 원장에 남은 건 0 으로 정리
--                                   · 창고 하나가 실패하면 즉시 중단 (오류를 12건 쌓지 않기 위해)
--   core.f_ec_customer_sync(by)     거래처 조회 → ec.customer
--   fn_ec_sync(what, whs[]) / fn_ec_sync_log(limit)
--
-- mvp_58b/c ────────────────────────────────────────────────────────
--   [발견] 이카운트 세션이 죽으면 JSON 이 아니라 IIS 412 HTML 이 온다 → 세션 만료로 판정해 재로그인
--   [발견] 로그인 성공 코드는 Data.Code = '00' 이다 ('000' 만 보고 있어 항상 실패로 기록됐다)
--   [발견] 세션 유효시간이 짧다 → 캐시를 50분에서 10분으로 줄임
--   응답의 QUANTITY_INFO(일일 허용량)를 ec.api_log.quota 에 저장
--
-- mvp_59_ec_circuit_breaker ────────────────────────────────────────
--   이카운트 제한 : **시간당 연속 오류 30건 / 1일 5,000건**. 넘기면 계정이 시간 단위로 막힌다.
--   core.f_ec_guard()               마지막 성공 이후 연속 실패가 ec.config.max_fail(기본 8) 이상이면
--                                   30분 자동 정지 + 이후 호출 거부 (errcode 55006)
--   ec.config.paused_until          정지 해제 시각 · fn_ec_resume() 으로 관리자가 수동 해제
--   재로그인 쿨다운 60초 · 재시도는 호출당 1회

-- mvp_60_inquiry_edit_flags ───────────────────────────────────────
--   crm.inquiry_flag(form, src_id, is_test, hidden, note)  원본 3개 테이블을 건드리지 않는 오버레이
--   core.f_looks_test(name, phone, text, handler)          테스트 자동 판별
--       · 이름/내용에 test·테스트·더미 · 홍길동/이순신/김철수 같은 더미 이름
--       · **고객명이 우리 직원 이름이면 본인 테스트로 본다** (지용현·차효범 등)
--       · 알려진 테스트 번호, 010XXXX 반복 패턴, 10자리 미만 번호
--   crm.v_inquiry 확장 : web_subscription(구독문의) 추가 · 견적은 **최신 버전만** · auto_test 컬럼
--   fn_inquiry_list(..., p_show)  real(기본) | test | hidden | all  + counts
--   fn_inquiry_flag(form, ids[], is_test, hidden, note)
--   fn_inquiry_save(form, id, data)   원본 테이블에 이름·연락처·담당·상태·내용 반영
--   fn_inquiry_delete(form, ids[], hard)  기본은 숨김(되돌리기 가능) · hard=true 는 관리자만
--
-- mvp_61_quote_number_parse ───────────────────────────────────────
--   [버그] 견적 GAS 가 시트 셀 값을 그대로 보내는데 "6,019,200" 처럼 **콤마가 든 문자열**이라
--          fn_submit_quote 의 ::numeric 캐스팅이 터졌다. GAS 는 muteHttpExceptions 로 삼켜서
--          "시트에는 쌓이는데 현행 시스템에는 안 들어오는" 상태가 계속됐다.
--   core.f_num(text) / core.f_int(text) 로 숫자만 뽑아 캐스팅하도록 교체.
--
-- 시트 백필 (2026-09-05) ──────────────────────────────────────────
--   견적내역        19건(견적번호 8개, 버전 포함)  → crm.quote
--   구독문의 상담관리 45건                          → crm.consult(web_subscription)
--   소모품·렌탈      2건 (테스트 4건은 함수가 자동 제외) → crm.consult(web_supply)
--   VMS·B2B         2건 (테스트 1건 자동 제외)       → crm.consult(web_b2b)
--   결과 : 실제 48건 / 테스트 12건

-- mvp_62_inquiry_columns ──────────────────────────────────────────
--   문의 목록이 "목적: X / 지역: Y / 메모" 한 덩어리라 읽기 어려웠다.
--   crm.v_inquiry 를 다시 만들어 kind(관심·상품) · purpose(목적) · region(지역) · memo 로 분리.
--   구독문의는 consult.content 에서 regexp 로 "목적:" "지역:" 을 뽑아내고 나머지를 메모로.
--   견적은 purpose 자리에 최종가·월구독료·버전을 넣는다.
--   fn_inquiry_list 기본 페이지 크기 50 → 25, 응답에 limit 포함.

-- mvp_63_dash_warm_presets ────────────────────────────────────────
--   [발견] 대시보드 캐시(core.dash_cache)는 정상 동작하나(예열 시 1~9ms, 미예열 1.5초)
--          fn_dash_refresh 가 "N개월 전 1일~오늘" 한 칸만 만들어서
--          화면 기본값인 **30일** 은 늘 캐시 미스였다.
--   화면이 실제로 쓰는 기간 버튼 6종 × 모드 2종 = 12칸을 미리 만들도록 교체.
--   샵링커 수집(collect.mjs)이 주문을 넣으면 캐시가 비워지므로,
--   수집 끝에서 fn_dash_refresh 를 불러 다시 예열한다.

-- mvp_64_pg_cron_jobs ─────────────────────────────────────────────
--   [발견] GitHub 예약 실행이 3~4.5시간씩 밀린다 (13:10 KST 슬롯 → 실제 17:48,
--          23:10 슬롯 → 실제 02:18/02:34). 그래서 Supabase pg_cron(설치돼 있음)으로 옮김.
--   core.f_dash_warm()  대시보드 캐시 12칸 예열
--   cron 'dash-warm'         매시 25분
--   cron 'ecount-stock-sync' 매일 03:00 KST — 창고별 재고현황 → kind='sync'
--   cron 'ecount-unpause'    15분마다 — 차단기 자동 해제
--   fn_cron_status(limit)    화면에서 실행 이력 확인
--
-- mvp_65_sl_order_pull ────────────────────────────────────────────
--   자동 수집된 샵링커 주문을 골라 주문서로 만드는 경로 (수기 입력 대체)
--   core.f_ec_code_of(name, model)  상품명/모델 → 이카운트 품목코드 4단계 매칭
--       ① 상품명 전체가 별칭과 일치 ② 모델코드가 별칭과 일치
--       ③ 모델코드가 품목 코드/모델과 일치 ④ 상품명 안에 별칭이 포함(긴 것 우선)
--       → 최근 3일 239건 중 201건(84%) 자동 매칭 확인
--   core.f_sl_pending(days,q,channel,limit)  아직 주문서로 안 만든 샵링커 주문 (주문번호 단위)
--   core.f_sl_to_order(order_nos[], wh, by)  골라서 큐 생성 + 재고 차감 (미매칭·재고부족은 건너뛰고 사유 반환)
--   fn_sl_pending / fn_sl_to_order          관리자
--   fn_store_sl_pending / fn_store_sl_to_order  담당자 PIN (perm='order')
--   fn_alias_add(alias, code)               못 찾은 상품명을 화면에서 바로 코드에 연결

-- mvp_66_menu_manager ─────────────────────────────────────────────
--   관리자 메뉴(왼쪽 네비)를 DB에서 관리한다. /admin → 옵션·권한 → "관리자 메뉴"
--   core.menu_group(code,label,sort,state,note)   6그룹 : _top/sales/crm/inv/data/ops
--   core.menu_item (code,group_code,label,sort,state,note)  18메뉴
--   state : 'on' 정상 · 'dev' 메뉴엔 보이되 누르면 공사 중 안내 · 'off' 메뉴에서 숨김
--   fn_menu()        로그인한 사람이 볼 메뉴 (off 제외) — admin.html 이 부팅 때 호출
--   fn_menu_admin()  관리자 편집용 (off 포함, sort/note 포함)
--   fn_menu_save(jsonb {groups:[],items:[]})  라벨·순서·상태·안내문구 일괄 저장
--   화면쪽: NAV_ICON(코드→아이콘), NAV_FALLBACK(DB를 못 읽어도 뜨는 기본 구성),
--          renderNav() / renderUnderConstruction() / #v-dev (공사 중 화면)
--
-- (화면) RPC 45초 캐시 ─────────────────────────────────────────────
--   admin.html 의 rpc() 가 조회 계열 결과를 45초 담아둔다. 저장 계열
--   (save/_set/delete/submit/sync/… )은 담지 않고, 실행되면 캐시를 통째로 비운다.
--   화면을 왔다갔다 할 때 같은 질의가 다시 나가지 않아 체감 속도가 붙는다.

-- mvp_67_dev_gate_menu ────────────────────────────────────────────
--   "메뉴를 보이게 할지 말지"는 개발자만 만진다.
--   개발자 계정  yonghyeon@samsungat.local (로그인 아이디 `yonghyeon`) · role=admin
--   core.app_setting['dev_users'] = 쉼표로 구분한 이메일 목록. 비우면 admin 전원 허용
--   core.f_is_dev()  admin 이면서 dev_users 에 든 계정만 true
--   fn_me() 에 is_dev 추가 → 화면이 [관리자 메뉴] 카드를 보일지 정한다
--   fn_menu_admin / fn_menu_save 는 f_is_dev() 로 잠금 (일반 admin 은 카드도 안 보이고 호출도 막힘)
--   화면: 3단 세그먼트 → **토글(메뉴에 보이기) + 라디오(공개 / 개발 중)**.
--         토글을 껐다 켜면 끄기 직전 상태로 돌아온다(o._prev). 그룹은 토글만.
--
--   [경로] 메뉴 관리는 관리자 화면 안이 아니라 **/admin/option** 독립 페이지.
--          web/admin/option/index.html (자체 로그인 · 미리보기 패널 포함)
--          web/admin/index.html 은 ../admin.html 로 보내는 리다이렉트 (경로 충돌 방지)
--          admin.html 의 [옵션·권한] 에는 링크 배너만 남고, 개발자 계정에만 보인다
--
-- (수정) 넓은 화면 정렬 ─────────────────────────────────────────
--   헤더는 폭 제한이 없고 본문(.view)만 1720~1840px 로 묶여 있어서, 2560px 같은
--   넓은 화면에서 헤더 오른쪽 표시(데이터 기준·최근 적재)가 카드보다 200px 쯤 더
--   오른쪽에 있었다. --maxw 변수 하나로 묶고 header/.content 에 같은
--   padding: max(28px, (100% - var(--maxw))/2) 를 줘서 좌우가 정확히 맞는다.
--   폭 상한도 화면에 따라 1720 / 1900 / 2100 / 2300px 로 단계를 늘렸다.
--
-- (수정) 개발자 계정 로그인 실패 ─────────────────────────────────
--   auth.users 를 SQL 로 직접 만들면 confirmation_token 등 토큰 칼럼이 NULL 이라
--   GoTrue 가 "Database error querying schema" 로 로그인을 거부한다.
--   해당 칼럼들을 '' 로 채워야 한다(정상 계정은 전부 빈 문자열).

-- mvp_68~70 : 옵션 모델 · 품목 후보 · 주문서 미리보기 ─────────────
--  [고침] fn_customer_list 가 STABLE 인데 실명보기 감사로그를 insert 해서
--         "INSERT is not allowed in a non-volatile function" 로 죽었다 → VOLATILE.
--
--  [옵션명이 진짜 모델명]  오픈마켓은 상품 하나에 서로 다른 모델을 옵션으로 붙여 판다.
--    예) 상품명 "천장형 에어컨 냉방 리모컨 AR-EC05" · 옵션 "AR-EH05(냉난방전용)"
--        → 실제 판매품은 AR-EH05. 상품명으로 매칭하면 다른 물건이 나간다.
--    core.f_model_in_option(option)  옵션 문자열에서 모델처럼 생긴 토막을 뽑는다
--        (5~24자 · 영문 포함 · 하이픈 또는 숫자 포함 · 순수 숫자 아님,
--         이카운트 품목으로 실제 풀리는 것 우선, 그다음 긴 것)
--    core.f_sl_model(model, option)  화면에 보여줄 "실제 모델"
--    최근 30일 2,833줄 중 108줄의 매칭이 바뀌었다 (AR-EC05→AR-EH05,
--    WD90F25CHW→WD90H25BHW, SM-R420NZAAKOO→SM-R420NZKAKOO 등 전부 교정)
--
--  [후보를 사람이 고른다]  같은 모델에 품목이 여러 개인 경우가 많다
--    (MLT-D111S → /TND · 1+1 · (재생) / CLT-K403S → 4색 패키지 · 1+1 · /TND).
--    자동으로 하나를 고르면 엉뚱한 게 나가므로 **후보를 다 주고 사람이 고른다**.
--    core.f_ec_cands(name, model, option) → [{code,name}] 순위:
--      ①옵션모델→별칭 ②옵션모델→품목 ③상품명전체→별칭 ④모델코드→별칭
--      ⑤모델코드→품목 ⑥상품명에 별칭 포함
--    최근 30일 기준 2,573줄 매칭 / 554줄은 후보 여럿(선택 필요) / 260줄 미매칭
--
--  [주문서 미리보기]  주문 1건 = 전표 1장. 만들기 전에 그대로 보여준다.
--    core.f_sl_preview(order_nos[], wh, picks) / fn_sl_preview · fn_store_sl_preview
--    picks = {"주문번호#줄번호":"품목코드"} — 고른 값은 f_sl_to_order 까지 그대로 간다
--    미리보기에 거래처·출하창고·특이사항·합계와 줄별 재고를 같이 보여주고,
--    품목 미정·선택 필요가 남아 있으면 [이대로 만들기] 를 막는다
--
--  (화면) 눌렀다는 게 보이게 : 상단 진행 바(#loadbar, rpc 진행 카운터),
--    버튼 눌림 애니메이션, "새로고침/조회" 버튼은 스피너 + 끝나면 완료 토스트.
--    모바일에서 .card h3 가 flex-nowrap 이라 설명 문구가 세로 한 줄로 눌리던 것도 고침.

-- mvp_71 : 자동 선택은 기존 맵핑으로 되돌림 ────────────────────────
--   f_ec_cands 의 **첫 번째 후보 = 기존 f_ec_code_of(상품명, 모델코드) 결과와 동일**.
--   옵션에서 뽑은 모델은 자동 적용하지 않고 후보 목록 뒤쪽에 opt=true 로만 붙는다.
--   후보 순위 ①상품명전체→별칭 ②모델코드→별칭 ③모델코드→품목 ④상품명에 별칭 포함
--              ⑤옵션모델→별칭 ⑥옵션모델→품목  (⑤⑥은 참고용)
--   최근 30일 2,780줄 기준 : 기존과 동일 2,466 / 새로 잡힘 53 / 옵션 대안 있음 121
--   남은 차이 12줄은 ec.product_alias 가 inv.item 에 없는 코드를 가리키던 것
--   (예: 'WD-FLTR', 'AT00609') — 주문서를 만들 때 어차피 "없는 품목" 으로 실패했을 건들.
--
-- (고침) 주문서·전송 화면이 비어 보이던 것 ────────────────────────
--   네비를 DB로 그리면서 주문서 메뉴의 뱃지(#badgeOq)가 없어졌는데 loadOq 가 그 요소를
--   붙잡다가 TypeError 로 죽어 표·건수·빈 안내가 모두 안 그려졌다. null 확인 + NAV_BADGE 등록.
--   빈 표에는 "아직 만든 주문서가 없다 · 샵링커 대기 N건" 안내와 바로가기 버튼을 둔다.

-- mvp_72 : 샵링커 가져오기 "statement timeout" ──────────────────────
--   [원인] 후보 목록(f_ec_cands)을 붙이면서 한 번 열 때 39초가 걸려 API 8초 제한에 걸렸다.
--     ① f_model_in_option 이 옵션 토큰마다 f_ec_code_of(4단계 조회)를 다시 돌림
--     ② f_sl_pending 의 CTE 가 인라인되어 f_ec_cands 가 줄마다 5~6번 평가됨
--     ③ 같은 (상품명·모델·옵션) 조합이 수백 번 반복되는데 매번 새로 계산
--     (어제까지 돌던 옛 함수도 4.5초쯤 걸려 제한 턱밑이었다)
--   [대책] 토큰 확인은 정확일치만 · 조합을 distinct 로 뽑아 한 번씩만 계산 ·
--          조합별 캐시 ec.cand_cache(별칭·품목이 바뀌면 트리거로 비움, 1일 TTL) ·
--          매시 예열(f_dash_warm)에 f_sl_pending(30일)을 넣어 늘 따뜻하게
--   [결과] 39초 → 처음 3.4초 → 캐시 후 0.9초. 7일 대기 590건 기준.

-- mvp_73 : 실수했을 때 되돌리기 ──────────────────────────────────
--   재고는 "지우는" 게 아니라 **반대 이동을 한 줄 더 쌓아** 되돌린다(inv.movement kind='in',
--   ref_type='order_void'). 그래서 언제 누가 무엇을 되돌렸는지 이력이 남는다.
--   ec.order_queue.batch_id  한 번에 만든 묶음 표시 'SL-YYMMDD-HHMISS-담당'
--   fn_order_void(id)                 한 건 취소 (기존)
--   fn_order_void_many(ids[])         여러 건
--   fn_order_void_batch(batch_id)     묶음 통째로 — sent(이카운트 전송됨)는 건너뜀
--   fn_order_batches(hours)           최근 72시간 묶음 목록 (화면 위쪽 "최근 만든 묶음")
--   화면 : 만들기 직후 결과 창에 [방금 만든 N건 되돌리기] · 주문서 페이지 위쪽 묶음 띠에
--          [되돌리기 N] · 둘 다 "되돌리기" 를 타이핑해야 눌린다. Esc/바깥 클릭으로는 안 됨.

-- mvp_74 : 단계별 주문 변환 (코드아이식 4단계) ──────────────────────
--   기존 빠른 모드(샵링커 주문 가져오기 모달)는 그대로 두고, 두 번째 모드를 붙였다.
--   ① 데이터 불러오기 (기간·날짜기준·채널·검색 · 이미 만든 것 포함 여부)
--   ② 데이터 선택   (주문 단위 체크 · 바로 가능/확인 필요/코드 없음/이미 만듦 필터)
--   ③ 코드 매핑     (같은 상품·옵션을 한 줄로 묶어 한 번에 지정 · 후보 select · 검색 · "기억"=별칭 저장)
--   ④ 변환 결과     (전표 미리보기 → 저장(재고 차감) · 관리자는 "저장 후 바로 이카운트 전송")
--   진행 상태는 브라우저에 저장 → 다시 열면 "작업을 이어서 진행할까요?" (코드아이와 같음)
--   관리자 admin.html : 왼쪽 메뉴 [주문 변환] (menu_item 'wiz', 재고 그룹) · 주문서 페이지 "단계별로 하기 →"
--   담당자 store.html : 주문서 탭 위 [빠른 모드 | 단계별 모드] 토글, 기본은 단계별
--   공용 코드 web/_wiz/wiz.js · wiz.css (마커 WIZ:*:BEGIN/END 로 두 파일에 인라인)
--   API : fn_sl_orders / fn_store_sl_orders (core.f_sl_range — 기간·기준일·완료포함)
--         fn_store_items · fn_store_alias_add · fn_store_warehouses (담당자용)
--   참고 : 코드아이 변환 결과(2026-09-04 18:05, 61줄)를 보니 고창재 프로가 AR-EC05 상품의
--          옵션 AR-EH05 건을 손으로 AT-00624 로 고쳐 넣었음 — 3단계 "옵션엔 AR-EH05" 표시가 그 자리.

-- mvp_75 : 담당자도 이카운트 전송 ────────────────────────────────
--   권한 'send'(이카운트 전송) 신설 — 관리자가 [옵션·권한]에서 사람별로 켜고 끈다.
--   지금 '주문서 등록(order)' 이 있던 박은지·고창재·지용현에게는 자동으로 켜 줌.
--   core.f_order_send(ids, by) 로 전송 본체를 공용화, 건별 결과(detail) 반환.
--   fn_order_send(관리자) · fn_store_order_send(p_code, ids)(담당자, perm='send')
--   fn_store_orders 에 can_send · pending_ids · slip · msg 추가.
--   화면 : 공용 확인창 ecSend() — "실제 전표가 생긴다 / 여기서 되돌릴 수 없다 / 실패는 대기로 남는다"
--          세 줄 + 확인 체크 후에만 버튼 활성, 전송 중 닫힘 방지, 끝나면 건별 결과표(전표번호·사유).
--          담당자 빠른 모드: "전송 대기 N건" 띠 + 행별 [전송] · 단계별 모드: 저장 뒤 [이카운트로 전송 (N장)]
--          관리자 주문서 페이지의 전송도 같은 창으로 통일.

-- mvp_76 : 자동 변환 ─────────────────────────────────────────────
--   "꼭 사람이 주문 변환을 해야 하나?" → 아니다. 시스템이 정할 수 있는 건 시스템이 한다.
--   core.f_sl_auto(days) : 최근 N일 샵링커 주문 중 아직 주문서 아님 · 모든 줄 후보 정확히 1개 ·
--     거래처코드 있음 · 재고 충분 → 주문서 생성(전송 대기). 애매/없음은 [주문 변환]에 남김.
--   스위치 core.app_setting['sl_auto'] (기본 off) · 일수 'sl_auto_days'(7) · 로그 core.sl_auto_log
--   pg_cron 'sl-auto' 매시 35분 · 자동 묶음은 'AUTO-…' (되돌리기 가능) · 알림 이벤트 sl.auto_made
--   관리자 API fn_sl_auto_set(on, days) / fn_sl_auto_run() / fn_sl_auto_status()
--   화면 : [주문서·전송] 위쪽 "자동 변환" 띠 (스위치 · 마지막 실행 결과 · 지금 한 번 돌리기)
--   최근 7일 634건 기준 자동 428(68%) / 확인 필요 128 / 코드 없음 78 — "기억"이 쌓일수록 자동 비율 상승
--   설명 문서 docs/주문변환-주문서-이카운트전송-설명.md (담당자·운영자·개발자용)

-- (화면) 뒤로가기 ──────────────────────────────────────────────
--   화면(admin)·탭(store) 이동을 history.pushState 로 쌓고 popstate 로 되돌린다.
--   전엔 replaceState 만 써서 뒤로가기가 사이트 밖(로그인 전 페이지)으로 튀었다.
--   첫 진입은 replaceState. 로그인 화면이 떠 있을 땐 popstate 무시.
--   제목 옆 [담당자 재고 화면 ↗] 같은 링크 — 관리자 화면 ↔ 담당자(대민) 화면 짝(STAFF_LINK).
--   store.html 은 #stock / #order / #daily / #consult / #online 해시로 바로 그 탭이 열린다.

-- (화면) 로그인 · 잠금 ───────────────────────────────────────────
--   로그인 : 왼쪽 영상(Pexels · Nicola Narracci, 무료 라이선스, 원격 링크) + 오른쪽 폼. 영상이 안 오면
--            캔버스 입자 애니메이션으로 대체(lgCanvas). 모바일은 영상 배경 위 카드.
--   잠금   : 세션은 12시간 그대로. 대신 (1) 자리 비움 30분 (2) 창을 닫았다 다시 열면
--            "잠금 화면"에서 비밀번호만 다시 — 하던 화면·상태는 그대로. (sessionStorage 로 새 창 감지)
--            담당자 화면도 같은 규칙으로 담당자 코드를 다시 친다.

-- mvp_77 : 카테고리·구분 ─────────────────────────────────────────
--   core.orders 에는 이미 category(12종: 필터·소모품/토너·잉크/청소기/…)와 goods_kind(대물/소모품/기타)가
--   상품명 규칙으로 채워져 있었다. 대기 목록(f_sl_range)에 실어 화면에서 나눠 보고 걸러 고른다.
--   주문 단위 category = 줄 중 최빈값, kind = 전부 소모품/전부 대물/섞임/기타.
--   inv.item.category 는 이카운트 분류코드(00001…)라 사람이 읽을 이름표가 아직 없음 — 분류코드 이름표를 받으면 붙일 것.
--   화면 : 담당자 빠른 모드를 표(헤더 전체선택 체크박스·구분·수량·금액·상태)로 · 구분/카테고리/상태 필터
--          단계별 2단계와 관리자 모달에도 구분·카테고리 열과 필터.

-- ═══════════════════════════════════════════════════════════════════════
-- mvp_78_pin_rate_limit  (v22)  담당자 코드(4자리) 무차별 대입 방지
-- ═══════════════════════════════════════════════════════════════════════
-- 방침 : 담당자는 들어오기 쉽게(4자리 그대로), 대신 틀린 횟수를 기기별로 세서 잠근다.
--   · core.pin_attempt(key, ip, device, code_hint, ua, at)  틀린 시도만 기록 (성공은 안 남김)
--   · core.f_req_ident()  요청 헤더에서 식별자 : x-dc-device(브라우저 localStorage 무작위 id) 우선, 없으면 x-forwarded-for(IP)
--       → 사무실처럼 여러 기기가 한 IP 를 써도 한 사람 실수로 전체가 잠기지 않는다
--   · core.f_staff(p_code)  VOLATILE 로 변경. 15분 안에 5회 실패 → '코드를 5번 틀려 N분 뒤에…' 예외(28000)
--       5회째에 core.f_notify('store.pin_lock', {key, ip, fails, last_code}) 발송, crm.access_log 에 store_code_fail 기록
--       모든 fn_store_* 가 f_staff 를 거치므로 별도 수정 없이 전부 적용
--   · public.fn_pin_attempts(p_hours=72)  admin 전용 : 기기별 실패 횟수/마지막/입력코드/잠김 여부
--   · public.fn_pin_unlock(p_key)         admin 전용 : 최근 15분 기록 삭제 = 즉시 잠금 해제
--   · pg_cron 'pin-attempt-prune' (10 4 * * *)  30일 지난 기록 정리
-- 화면 : store.html  createClient(..., {global:{headers:{'x-dc-device': DEVICE_ID}}}),
--        잠김 메시지 받으면 입력칸 비활성 + 남은 시간 카운트다운(localStorage dc_pin_until 로 새로고침해도 유지)
--        admin.html 옵션·권한 → '매장 코드 오입력 · 잠금' 카드 (fn_pin_attempts / fn_pin_unlock)
-- 주의 : 카운트다운은 화면 추정치(서버가 기준). 관리자가 풀어주면 화면은 새로고침해야 풀린다.

-- ═══════════════════════════════════════════════════════════════════════
-- mvp_79_pin_record_autonomous_ec_throttle  (v23)
-- ═══════════════════════════════════════════════════════════════════════
-- [버그] 코드 틀려도 "4번 더 틀리면" 이 안 줄던 이유
--   f_staff 가 pin_attempt 에 insert 한 뒤 raise exception → PostgREST 트랜잭션이 통째로 롤백되어 insert 도 사라짐.
-- [해결] 실패 기록을 '자기호출' 로 따로 커밋
--   core.f_pin_fail_post(p)  : extensions.http() 로 우리 PostgREST(/rest/v1/rpc/fn_pin_fail_record) 를 호출 → 별도 트랜잭션에서 커밋
--   public.fn_pin_fail_record(p) : 헤더 x-dc-internal 이 vault 'dc_internal_token' 과 같을 때만 core.f_pin_fail_record 실행 (아니면 42501)
--   core.f_pin_fail_record(p) : pin_attempt insert + crm.access_log + 5회째 f_notify('store.pin_lock')
--   core.app_setting 'anon_key' : 자기호출 apikey (공개값)
--   notify_rule 'store_pin_lock' 추가(기본 꺼짐 · jandi_ops)
--   테스트 : 같은 키로 5회 → 5건 기록, 6회째는 잠금 예외

-- ═══════════════════════════════════════════════════════════════════════
-- mvp_80_menu_env_test_prod  (v23)  테스트/배포 환경
-- ═══════════════════════════════════════════════════════════════════════
--   core.menu_item.envs / menu_group.envs text[] default '{test,prod}'
--   fn_menu(p_env)  : 'test' 는 /admin/test/, 그 외 /admin.html — 화면이 location.pathname 에 /test/ 가 있으면 test 로 부른다
--   fn_menu_admin / fn_menu_save : envs 왕복
--   파일 : admin/test/index.html = admin.html, store/test/index.html = store.html (build.sh 가 복사). 상대 링크는 모두 절대경로(/store.html …) 로 바꿈

-- ═══════════════════════════════════════════════════════════════════════
-- mvp_81_ec_stock_sync_queue  (v23)  이카운트 재고 동기화 — 창고 하나씩 3분 간격
-- ═══════════════════════════════════════════════════════════════════════
-- [관측] 재고 API(GetListInventoryBalanceStatus) 를 짧은 시간에 3~5번 부르면 이카운트(IIS) 가 HTTP 412(HTML) 로 끊고,
--        그 뒤 몇 분 동안 계속 412. 재로그인해도 소용없고 '가만히 두면' 풀린다. 1.2초 간격도 소용없음.
--        1일 허용량(5000) 과는 별개. 0행 창고 조회는 이카운트가 '연속 오류' 로 센다(30/시간 넘기면 계정 잠김).
-- [설계] ec.stock_sync_run / ec.stock_sync_task
--   core.f_ec_stock_enqueue(by, whs)  : 실행 중이면 그 run 반환, 아니면 활성 창고 전부 todo 로
--   core.f_ec_stock_step()            : todo 하나 처리 (core.f_ec_stock_sync_wh). 실패는 attempts+1 후 뒤로, 4회 넘기면 fail. 남은 게 없으면 run 마감 + ec.sync_log 1줄
--   core.f_ec_stock_sync(whs, by)     : 호환용 — enqueue 로 위임
--   public.fn_ec_sync('stock')        : 줄만 세우고 즉시 반환 {queued:true,total}
--   public.fn_ec_stock_progress()     : 마지막 run 진행 상황 (관리자 이카운트 카드에 진행바)
--   cron 'ecount-stock-sync' 0 18 UTC → enqueue('pg_cron') ; 'ecount-stock-step' */4 * * * * → step()
-- mvp_82 : 실측 — 8분 쉰 뒤 65초 간격으로 3번은 성공, 4번째 412. 막힌 상태에서 또 부르면 막힘이 연장됨(3분 간격으로 불러도 계속 412).
--          → 4분 간격 + 412 맞으면 run.paused_until = +10분 쉬고 이어감. 12창고 ≈ 48분 (03:00 → 03:50 무렵 끝)
--   f_ec_call : 412 즉시 재시도 제거(의미 없음). f_ec_guard : 412 는 연속 실패로 안 셈(30분 멈춤 방지)
-- mvp_83_pin_fail_dedupe (v24) : 코드 한 번 틀린 게 2~4건으로 잡혀 2회 만에 잠기던 문제
--   원인 ① 화면이 status·quotes 두 RPC 를 병렬로 → 실패 2건  ② input 이벤트와 Enter 가 겹쳐 두 번 전송
--   서버 : 같은 기기·같은 코드가 1.5초 안에 또 오면 한 번으로 셈 (5초는 같은 코드를 연달아 치면 안 세져서 줄임). 화면 : status 먼저, quotes 는 성공 뒤 · 전송 중 재전송 막음
--   화면 잠금 표시는 남은 시간만 보여주고 입력은 막지 않음 — 관리자가 fn_pin_unlock 으로 풀면 바로 다시 들어감 (판단은 서버)

-- ═══════════════════════════════════════════════════════════════════════
-- mvp_84_store_order_request  (v25)  매장 판매 → 이카운트 주문서 요청 → 처리 담당자 알림
-- ═══════════════════════════════════════════════════════════════════════
-- 흐름 : 매장 담당자가 /store 판매 입력에서 '이카운트 주문서 요청'(기본 켜짐) 을 두고 저장
--        → ec.order_request(open) + f_notify('store.order_request') (잔디 규칙 store_order_request, 기본 꺼짐)
--        → 처리 담당자(권한 entry: 고창재·박은지·지용현 부여, 옵션·권한에서 조정) 의 /store 는 60초마다 fn_store_requests 로 확인
--          주문서 탭 배지·탭 제목 (N)·토스트·진동. 주문서 탭 맨 위 '매장 판매 요청' 카드에서
--          [주문서로](직접 입력 칸에 코드 후보·수량·단가 채움, 등록하면 request_id 로 자동 처리됨) / [내가 맡기] / [직접 처리함] / [불필요]
--        → 요청자는 홈 '내 주문서 요청' 카드에서 대기·처리 중·처리됨 확인
--   perm_def 'entry' 주문서 처리 담당 (default off)
--   ec.order_request(id, requested_by, sale_order_id, product_name, model_code, qty, amount, cust_*, status open|taken|done|skip, taken_by, done_by, queue_id …)
--   fn_store_sale_submit(p_data.request_order) · fn_store_requests(code) · fn_store_request_take · fn_store_request_close(code,id,'done'|'skip',note,queue_id)
--   fn_store_order_submit(p_data.request_id) → 등록 성공 시 요청 done + queue_id
--   fn_order_requests(limit) 관리자 주문서·전송 화면 상단 카드
-- [버그 수정] store.html 에 옛 한 줄짜리 goTab(t){click()} 이 새 goTab(name,fromHistory) 를 덮어써 v21~v24 에서 탭이 안 바뀌던 것 제거
-- 로그인 화면 : 아이디 placeholder 가운데 4자리 * 처리, '아이디만 입력해도' 문구 삭제
-- mvp_85_pin_flow_natural (v26) : 코드 맞게 들어오면 그 기기의 실패 기록 삭제(초기화) · 경고 문구는 2번 남았을 때부터만
--   fn_store_* 중 STABLE 이던 4개(daily_list·report·customer_search·warehouses) → VOLATILE (f_staff 가 delete 하므로)
--   화면 : 다시 입력 시작하면 오류 문구 지움 · 잠금 풀리면 "이제 다시 입력할 수 있습니다"
-- (v27) 코드 화면 : 서버 오류문에 (N/5) 를 항상 넣고 화면이 빨간 5칸 눈금으로 표시 · 확인 중 스피너/입력 잠금 · 성공 토스트 "OO님, 확인됐습니다"
--        같은 탭 새로고침은 <html class="resuming"> 로 코드 화면을 아예 그리지 않고 이어감(깜빡임 제거) · 새 탭이면 코드 화면부터
--        [버그] v25 에서 요청 목록 CSS .req 가 판매 입력의 필수표시 .req 와 겹쳐 라벨이 깨짐 → .rq 로 변경
-- (v28) 발송 대상 추출 : 유입을 고도몰(P·S·AT·시흥) / 외부 ERP·수집(이카운트·샵링커) / 내부 운영(매장·상담·렌탈) / 홈페이지 폼(구독·견적서·VMS·B2B·소모품) 으로 묶어 표시 (화면 CRM_SRC)
--        S몰·AT몰은 회원 파일 미적재라 0 으로 나옴. 헤더 적재시각 팝업 : 모바일에서 hover 가 붙어 안 닫히던 것 → 탭 토글 + 바깥 탭 닫힘 + 닫기 버튼
-- cron 추가 : ecount-master-sync 0 0,12 UTC (09:00·21:00 KST 품목+거래처) · ecount-stock-sync-pm 10 12 UTC (21:10 KST 재고 줄세움)
--   ※ 이카운트 '판매현황'(VMS·렌탈 매출) 조회 API 는 확인되지 않음 → 여전히 파일 업로드. 이카운트 API 목록에 판매조회가 있으면 붙일 것
-- 첫 큐 실행 결과 : 12창고 06:56→07:44 (48분) 전부 성공, 779행, 조정 2건

-- ═══════════════════════════════════════════════════════════════════════
-- mvp_86_consult_hide_and_store_actions  (v29)
-- ═══════════════════════════════════════════════════════════════════════
-- [상담 숨김] crm.consult.hidden_at/by/reason + 뷰 crm.consult_live (hidden_at is null)
--   읽기 함수 8개(fn_store_status·fn_store_customer_search·fn_consult_summary·fn_consult_routes·fn_home·fn_dashboard_kpi·fn_dashboard_v2·fn_activity_log)
--   본문의 crm.consult → crm.consult_live 로 치환 → 담당자 화면·통계에서 자동 제외. 관리자 fn_consult_list 는 기본 제외, p_result='숨김' 이면 숨긴 것만 (hidden_* 컬럼 추가, 반환형 바뀌어 drop 후 재생성)
--   fn_consult_hide(ids, hide, reason) · 문의 관리 fn_inquiry_flag(테스트/숨김) 도 구독·소모품·B2B 폼이면 상담에 같이 반영
-- [담당자 상담 처리] fn_store_consult_update(code, id, 'hold'|'callback'|'resume'|'close', at, memo)
--   보류 → result 보류 / 재연락 → callback_at (콜백 약속 카드에 뜸) / 다시 진행 / 종료. 내 상담 또는 callback 권한
--   fn_store_status.my_open_consults 에 result 추가. 화면 : 진행중 상담 카드에 [재연락][보류][종료] + 빠른 일정(오늘 2시·내일 10시…)

-- mvp_87_gifts (v30) 사은품
--   crm.consult / core.orders : gift_name, gift_amount · crm.gift_preset(name, price, uses, last_used_at) — 한 번 쓰면 자동 등록, 많이 쓴 순으로 칩
--   fn_store_gifts(code) → {presets, links} · fn_gift_presets() 관리자 · app_setting 'gift_links' (문의 시트·오피스콘·스타벅스·신세계·오피스콘 계정) 관리자 옵션에서 편집
--   fn_store_consult_submit / fn_store_sale_submit 에 gift_name·gift_amount → 저장 + core.f_gift_touch. fn_consult_list 에 gift 컬럼(반환형 재생성)
--   오피스콘 계정은 HTML 에 넣지 않고 DB 에서 코드 통과 후 RPC 로만 내려줌 ('오피스콘 계정 보기' 버튼)
-- (v31) 홈 고객 카드 : 발송 가능(전체) · 개인/기업 (fn_home.counts cust_* — crm.customer.account_type personal/business, 발송가능=수신동의+휴대폰)
--        데이터 기준 '~09-20' 오류 : 렌탈 업로드 1행(id 170151, 전표 2026/08/10)이 order_at 2026-09-20 으로 들어와 있었음 → 08-10 로 보정
--        fn_data_stamp / fn_data_status 의 max(order_at) 에 filter (where order_at <= now()) — 미래 날짜가 또 들어와도 기준일에 안 잡힘

-- mvp_88_inv_excluded (v32) 재고 집계 제외
--   inv.item.excluded / excluded_note. 자동 규칙: 이름에 수수료·운송료·배송비·수리비·기술료·출장비·포인트·할인·설치비·추가요금·카드매출… 또는 '기타', item_type='7' → 26품목 제외
--   fn_inv_summary : 제외 품목 빼고 집계 (+excluded 수) · fn_inv_stock(…, p_show_excluded) 기본 제외, 켜면 제외 품목만 (반환형 같아 drop 후 재생성)
--   fn_inv_item_exclude(codes, excluded, note) 관리자 행 버튼 [집계 제외]/[집계 포함] · fn_stock_search 담당자 화면에서는 아예 안 보임
-- 화면 공통 : 모든 표 머리글 클릭 정렬(오름/내림, 숫자·한글 자동 판별, 현재 페이지 행 기준). 소계 줄(colspan) 있는 표는 제외. admin·store·stock 세 파일

-- (v34) 공통 검색·필터 바 + 고객 통합 수정
--   [버그] fn_customer_stats : by_freq/new_by_month 의 group by 1 이 집계식이라 42803 → CTE 로 분리 (고객 통합 '유입 채널별·구매 횟수 분포' 빈 화면 원인)
--   fn_order_list / fn_order_summary : p_category(core.orders.category), p_q_field(product|customer|model|order_no|phone|handler|channel) 추가 (drop 후 재생성)
--   화면 : 목록 화면 12개 맨 위 공통 바 [기간][검색유형][검색어][채널][상품유형][조회][초기화] (CB_VIEWS)
--          서버가 받는 조건은 서버로, 모르는 조건은 화면 표에서 행 숨김(MutationObserver 로 재적용) · 화면 바뀌면 조건 초기화 · 화면 자체 검색칸은 숨김
--   고객 통합 '유입 채널별' 도 CRM_SRC 표기(S몰·AT몰 0 포함)
-- (v36) 고객 통합 : 발송 가능 카드(개인/기업) · 유입/구매횟수 막대에 전체(회색) 위 발송 가능(색) 겹침 (fn_customer_stats sendable 추가)
--   이카운트 거래처 조회 API : /OAPI/V2/AccountBasic/GetBasicCustomersList 등 5개 경로 전부 404 → OpenAPI 에 거래처 조회가 없는 것으로 보고 api_def 'customer' 비활성
--   ecount-master-sync 크론은 품목만 (09:00 실행이 거래처 404 로 통째로 실패해 품목도 롤백됐던 것 수정). 홈 데이터 상태에 재고 동기화·품목 줄 추가
-- (v37) 담당자 화면 : 진행중 상담의 고객 이름 → 같은 고객으로 상담 입력(후속) 열기 · 사은품 링크(오피스콘·상품권·계정)는 오른쪽 아래 🎁 플로팅 버튼으로
-- 이카운트 조회 API 탐색 결과 : 판매/주문서 조회 후보 경로 6개 전부 404 (Sale/GetListSale 등). 확인된 조회 API 는 품목·창고별재고 둘뿐
-- 판매현황(8/1~9/7, 3,880행) vs 주문서 현황(9월 317건, 전부 '생성한전표') 대조 : 판매현황 ≈ 주문서→판매 전환분(온라인 2,666 + VMS/택배 ~960) + 소수 직접입력.
--   온라인분은 샵링커 원장과 중복이므로 업로드 파서는 VMS 행만 적재(8월 822행). VMS 도 이카운트 주문서로 입력되고 있음 → 우리 화면에서 입력해 전송하면 업로드 자체가 불필요

-- ═══════════════════════════════════════════════════════════════════════
-- mvp_91_order_send_ecount_format  이카운트 주문서(SaveSaleOrder) 첫 실전송 성공 — 2026-09-07 11:00, 전표 20260907-15 (테스트, 이카운트에서 삭제)
-- ═══════════════════════════════════════════════════════════════════════
-- 형식 : SaleOrderList[{BulkDatas:{...}}] 라인마다 1개, 같은 UPLOAD_SER_NO(=queue id) 면 한 전표. core.f_order_body(id) 로 생성
-- 이카운트가 돌려준 검증 오류로 확정한 규칙 :
--   U_MEMO1(모바일) 필수 → 없으면 010-0000-0000 · ADD_TXT_01_T(특이사항)·U_TXT1(주소)·REMARKS 는 특수문자 불가(한글·영숫자·공백 ,.()/- 만)
--   USER_PRICE_VAT = '단가(vat포함)' 숫자 컬럼 (Y/N 아님!) → 여기에 VAT 포함 단가를 넣고 PRICE 는 보내지 않는다
-- 응답 : Data.SuccessCnt/FailCnt/SlipNos[]/ResultDetails[].Errors[{ColCd,Message}] → FailCnt=0 일 때만 sent, 오류는 ColCd+Message 로 저장
-- 아직 안 보내는 것 : EMP_CD(영업담당 코드, 예 00072 박은지) · IO_TYPE(거래유형 코드 — 직판/자체VMS/VMS/임대/스마트스토어 B2B… 코드표 필요) · 판매담당자 · 구분(카드) · 주문No.
-- mvp_92 (v38) 전송된 주문서 취소 : f_order_void_many(..., p_sent_ok) / fn_order_void_many(ids, reason, sent_ok). 관리자 주문서 행 [취소 (이카운트 삭제 후)] — '삭제했음' 입력 필수
--   이카운트 화면 대조 : U_MEMO1 = '특이사항' 칸이었음(모바일 아님). 공급가액·부가세는 자동 계산 안 됨 → SUPPLY_AMT·VAT_AMT 를 보내야 함(다음 수정)
--   필드 확인용 전표 1건 추가 전송(시흥몰(필드 확인 테스트), U_MEMO1~5/U_TXT1/ADD_TXT_01~05/DOC_NO/TTL_CTT/REF_DES/REMARKS_WIN/P_REMARKS1~3 에 표식) — 화면에서 자리 확인 후 매핑 확정

-- ─────────────────────────────────────────────────────────────
-- mvp_95 (2026-09-07) 담당자 화면 샵링커 엑셀 업로드 허용
--   core.f_orders_bulk_upsert(p_source,p_file_name,p_rows,p_by uuid,p_note) : 관리자/담당자 공용 본체 (anon·authenticated 실행 불가)
--   public.fn_orders_bulk_upsert : 관리자 전용 래퍼 (기존 시그니처 유지)
--   public.fn_store_orders_upload(p_code,p_file_name,p_rows) : PIN 담당자 · source='shoplinker' 고정 · 500행/회 · raw.upload.note='담당자 업로드: 이름'
--   fn_upload_history.by = profiles.email 없으면 upload.note (담당자 업로드 표시)
--   store.html : 주문서 탭 단계별 모드 "파일 업로드" 드롭존 + 빠른 모드 "샵링커 엑셀 올리기" 링크. xlsx 모듈은 필요할 때만 CDN 로드.
--   v39 프런트 : 재고 탭 fn_stock_search 페이징(50)·분류·재고있는것만 / 최근 마감 [수정][삭제] (fn_store_daily_get/delete) /
--               샵링커 가져오기 목록 50건 페이징 / 단계별 변환 ② 선택 100건 페이징 (admin·store 공용 wizMount)

-- ─────────────────────────────────────────────────────────────
-- mvp_96 (2026-09-07) 주문서 직접 입력 폼 = 이카운트 주문서 입력 항목 (전체 SQL: sql/mvp_96_order_form.sql)
--   ec.code(kind emp|io_type|kind, code, label) 코드표 · fn_ec_codes_set(p_kind,p_rows) · 관리자 옵션·권한 → 주문서 코드표 카드
--   ec.customer ← 이카운트 거래처 엑셀(데이터 가져오기, 자동 인식 '거래처코드'+'거래처명') fn_ec_customers_upsert · 쇼핑몰 거래처 15곳 channel_cust 에서 seed
--   fn_order_meta() / fn_store_order_meta(p_code) · fn_ec_customer_search / fn_store_ec_customers · fn_item_resolve / fn_store_item_resolve(품목명→코드, 후보)
--   order_queue.handler(판매담당자)·kind_code(구분) · order_queue_line.supply_amt·vat_amt (합계/1.1 반올림, 나머지 부가세)
--   f_order_body : app_setting 'ec_field_map' {phone,addr,remark,handler,kind,order_no,channel → 이카운트 필드} + SUPPLY_AMT/VAT_AMT 전송. 관리자 이카운트 카드에서 매핑 수정
--   화면 : _of/of.js·css 를 admin.html/store.html 에 마커(OF:JS:BEGIN)로 인라인. admin 의 "+ 직접 입력" 은 openOqModal() (기존 openOrderModal 은 원장 수동등록과 이름이 겹쳐 엉뚱한 창이 열리던 버그 수정)

-- ─────────────────────────────────────────────────────────────
-- mvp_97 (2026-09-07) 전체 SQL: sql/mvp_97_sets_slips.sql (+ 97d resolve 권한, 97e order_ref)
--   영업담당 코드 30개 seed(ec.code emp) · 거래유형 표준 seed 비활성(이 회사 거래유형=채널명 관리항목, 코드는 담당자가 [+ 추가])
--   fn_ec_codes_add / fn_store_codes_add : 담당자도 코드 추가. 이카운트에 없는 코드면 전송 실패 → 별도 등록 필요 안내
--   core.orders.alt_order_no(자사주문번호=이카운트 주문No.) · tracking_no(송장) — 자동수집(fn_sl_upsert)·엑셀 파서 모두 채움
--   ec.slip_ref ← 이카운트 주문서 현황 업로드(fn_ec_slips_upsert, 자동 인식 '일자-No.'+'주문No.') → f_ec_slip_of 로 "이카운트 등록" 판정, 샵링커 목록에서 done 처리
--   f_sl_range : shipped(송장전송완료/송장번호/shipped_at) · ec_slip · unshipped/shipped 건수 → 담당자·관리자 목록 발송/미발송 필터
--   inv.item.no_stock(직배송 미차감) fn_inv_item_no_stock · inv.item_set 세트 구성(fn_inv_sets / fn_inv_set_save, 이름 규칙 자동 20개)
--   f_order_submit : 세트 → 구성품 줄로 확장(금액 비율 분할, 나머지 첫 줄), no_stock/대물 줄은 재고 안 뺌, line_total 우선
--   f_sl_to_order : 단가 = 샵링커 주문금액/수량, line_total = 주문금액 (이카운트 금액 = 실결제), 대물 no_stock, 이미 이카운트 등록이면 건너뜀, order_ref
--   f_order_body : deal_type/order_ref 도 매핑 키 · 매핑 화면에 거래유형·자사주문번호 추가
--   화면 : 주문서 폼 [+ 추가]·세트/재고미차감 태그, 담당자 재고 탭 붙여넣기 일괄 입출고, 품목 화면 세트 구성 카드·재고 미차감 버튼, 데이터 가져오기 주문서 현황

-- mvp_98 (2026-09-07) 주문서 현황 → 거래처·거래유형·구분·판매담당 자동 채움
--   fn_ec_slips_upsert 끝에 core.f_ec_seed_from_slips(): 거래처명(코드 모르면 'N:이름' 임시코드, source='slip', 전송 때 CUST 없이 이름만),
--   쇼핑몰 거래처는 f_slip_cust_alias 로 channel_cust 코드에 매핑해 기본 거래유형·영업담당만 채움, 거래유형·구분은 값 그대로 코드표(코드=이름, 실제 코드 알면 코드표에서 수정)
--   f_order_meta.staff = 담당자 마스터 ∪ 주문서 현황 판매담당 · f_sl_to_order 는 채널 거래처의 기본 거래유형·영업담당을 넣음
--   9/1~9/7 주문서 현황(316건) 적재 완료 → 거래처 58곳(쇼핑몰 15 + 코드 없는 43), 거래유형 14, 구분 1(카드)

-- mvp_99 (2026-09-07) 이카운트 거래처 마스터(거래처 코드.csv, 51,711건) 적재 준비
--   ec.customer + sales_handler(판매담당자)·device(사용기종)·active · pg_trgm 이름 인덱스 · 검색은 앞글자 일치 우선/사용 중만
--   fn_ec_customers_upsert : 담당자명→사원코드, 거래유형(영업)→deal_type, 같은 이름의 임시(N:) 거래처 삭제. admin 파서 별칭(핸드폰번호·담당자명·판매담당자·사용기종·거래유형(영업)), csv 는 raw 로 읽어 코드 앞 0 보존
--   거래유형 26개(거래처 마스터의 거래유형(영업) 값) seed. 거래처 고르면 판매담당자·모바일·주소도 함께 채워 전송(U_MEMO1/U_TXT1)
--   적재는 관리자 데이터 가져오기에 '거래처 코드.csv' 올리면 자동 인식(약 130회 분할 호출, 수 분)

-- mvp_100 (2026-09-07) 발송일 기준
--   f_orders_bulk_upsert 가 shipped_at 을 받음(파서: 발송완료일·_송장등록일) · f_sl_range p_basis='ship'(발송일 기준 조회) · 행에 shipped_on·late(주문 다음 달 발송) · 집계 late
--   화면: 단계별 변환 날짜 기준에 "발송일 (송장)", 발송 필터에 "주문 다음 달에 발송", 발송 태그에 날짜. 불러오기 상한 3000건, 담당자 빠른 목록 30/60일·1000건
--   8월 원장은 9/3 업로드본이라 발송일이 비어 있음 → 최신 샵링커 파일(7월~현재)을 다시 올리면 채워짐(같은 주문번호는 갱신)

-- mvp_101 (2026-09-07) 규칙: 송장(발송) 없는 주문은 이카운트에 올리지 않는다 (app_setting sl_require_ship=on)
--   f_sl_pending(빠른 목록) = 발송일 기준 최근 N일 · f_sl_auto 도 발송일 기준 · f_sl_to_order 는 미발송이면 "미발송 (송장 없음)" 으로 건너뜀
--   단계별 변환 ② 발송 필터 기본값 = 발송됨. 수집기(collect.mjs)는 이미 송장등록/송장전송완료 이벤트일 기준으로 최근 3일 치를 매번 가져오므로 뒤늦게 송장 찍힌 옛 주문도 갱신된다

-- v48 화면 (2026-09-07) 조회 조건 한 곳: 공통 바(기간 · 검색/채널/상품유형 · 화면별 필터)로 통합 — placeCbar 가 각 화면 첫 카드의 .filters 안 필터 요소를 #cbExtra 로 옮기고(cbarPull), 화면 전환 때 되돌림(cbarRestore). 화면 자체 조회·초기화 버튼은 숨김. 문의 관리 "상단 기간 적용" 스위치 제거(항상 적용)
-- mvp_102 (2026-09-07) 샵링커→주문서 io_date = 발송(송장전송)일, 없으면 주문일 · core.orders.shipping_fee 컬럼 준비(배송비 — 파서/수집기 매핑과 이카운트 배송비 품목코드 확정 대기)
-- v49 화면 (2026-09-07) 관리자 화면 안 섹션 탭: 카드(h3)가 둘 이상인 화면은 헤더 아래 #subTabs 에 카드 제목 탭을 만들고 누르면 그 카드로 스크롤·현재 위치 표시 (buildSubTabs, refreshView 뒤 갱신)
-- v50 화면 (2026-09-07) 담당자 화면에도 탭 안 섹션 탭(#subTabs, 카드 h2 둘 이상일 때 탭 바 아래)
-- mvp_103 (2026-09-07) core.f_role(): 서비스 롤 JWT 면 'admin' — GitHub Actions data-freshness(check-freshness.mjs → fn_data_status) 403 수정. 파일 변경 없음
-- mvp_104 (2026-09-07) 매장 판매 입력 상품 여러 줄: fn_store_sale_submit p_data.items[{product_name,model_code,qty,amount}] → 같은 주문번호 line 1..n, 요청(ec.order_request.items) 한 건, fn_store_requests 가 줄마다 후보 코드 → 주문서로 넘기면 줄 전부 채움
-- v51 화면 : 판매 입력 [+ 상품 추가] · 요청 카드 줄별 표시 · 담당자 섹션 탭 디자인(밑줄형·가운데·14px)
-- mvp_105 (2026-09-07) fn_store_items: sale 권한도 허용 · 코드/모델/이름 검색, 앞부분 일치 우선 (판매 입력 상품명·모델코드 자동완성)
-- v52 화면 : 담당자 재고 탭 순서 = 입고·출고 → 최근 입출고 → 현재고(검색 맨 뒤). 빠른 입·출고(품목 찾기 → 수량 → [입고]/[출고], 세트는 구성품 자동 분해),
--            붙여넣기 일괄은 접이식으로 그 안에. 판매 입력 상품명·모델코드에 등록 품목 자동완성(itemSuggest)
-- v53 화면 : /dash/ 사내 로그인 자동 열람 — 같은 도메인 localStorage 의 sb-*-auth-token 이 살아 있으면
--            비밀번호 화면 없이 Bearer 토큰으로 fn_dash_payload(p_from,p_to,p_mode) 호출. 실패하면 기존 비밀번호 화면으로 되돌아감.
--            SHARE_URL(기존 app GAS) 미설정 상태에서는 출처 토글을 숨기고 dash_src='gas' 세션값도 지움 → "GAS 공유 주소" 안내가 뜨지 않음.
-- v53 배포 경로 : dash 도 test/prod 두 벌 — /dash/test/index.html(테스트) · /dash/index.html(배포).
--            admin 화면의 DASH_DIR 가 DC_ENV 를 보고 iframe(embed=1)·외부 공유 링크를 각각 /dash/test/ · /dash/ 로 건다.
--            (기존에는 iframe src 가 상대경로 'dash/index.html' 이라 /admin/test/ 에서 404 였다 → 같이 고침)
-- v56 화면 : 주문 변환 하단 안내 문구(.wiz-ft .note)가 좁은 폭에서 세로로 잘리던 문제 —
--            note 를 남는 폭 전체로 늘려 가운데 정렬, 최대 두 줄까지만 보이고 전체 문장은 title 로. 버튼은 줄바꿈 없이 고정.
-- mvp_106 (2026-09-07) core.f_sl_range 요약 숫자를 서로 겹치지 않게 :
--   'ready'     = mapped=total_lines AND ambig=0  (기존에는 모호한 건도 포함돼 확인 필요와 겹쳤음. 겹치던 값은 'ready_all' 로 남김)
--   'ambig'     = ambig>0 AND mapped=total_lines  (코드 없음이 섞인 주문은 '코드 없음' 쪽으로만)
--   → 바로 가능 + 확인 필요 + 코드 없음 = 아직 안 만든 주문 수. (8/31~9/7 : 429 + 101 + 64 = 594)
-- 확인 필요의 실제 원인 = 이카운트 품목 마스터가 같은 모델을 둘 이상 갖고 있음
--   ① 중복 등록 : HA-MTSHELFWHT(AT-00993/AT-00611) · WD-FLTR(AT-00651/AT-00607) · ACM-B1M1SC(AT-00722/AT-00564)
--   ② 단품 vs 세트/1+1/4색 패키지 : CLT-K515S(4색 패키지 / 1+1) · CLT-K510S((SET) / 1+1) · CLT-K2430S(4색 패키지 / 단품)
--   ③ 정품 vs 재생 : MLT-D111S((재생) / 1+1)
--   ④ 상품명과 모델코드가 가리키는 물건이 다름 : 제트봇 물걸레포 VCA-RPW97 / VCA-RPWF90
--   → ①은 이카운트에서 품목을 정리하면 사라지고, ②③④는 ec.product_alias 에 별칭을 넣으면 자동 확정된다.
-- mvp_107 (2026-09-07) fn_home 'uploads' : 큰 파일은 500행씩 나눠 올라와 raw.upload 행이 조각마다 생겼다
--   → source + file_name + 시(hour) 로 묶어 한 줄로. rows/skipped 는 합계, 조각 수는 'chunks' 로 내려준다.
--     (예: member_list…6846.xls 17조각 → 8,073행 · 제외 275) 화면은 파일명 옆에 "N조각" 태그.
-- v58 화면 : 담당자 🎁 사은품 버튼은 판매 입력·상담 입력 탭에서만 표시 (PIN 화면·다른 탭에서는 숨김)
-- mvp_108 (2026-09-07) 홈페이지 문의 = 고도몰 홈페이지 '개인·사업자 가전 견적' 게시판 (구독 문의와 분리)
--   crm.web_inquiry (ref_no, name, phone/phone_key, email, inquired_on, kind 개인/사업자, status 진행/완료/대기,
--                    quote_result 미입력/success/failure, handler, channel='홈페이지', note, buyer_key)
--   유니크 = (phone_key, inquired_on, name) → 여러 번 붙여 넣어도 갱신만. crm.f_date_loose('2026. 7. 10' / '2026-08-19' 둘 다)
--   core.f_web_inq_upsert(p_rows) · public.fn_web_inquiry_upsert(p_rows) (admin/dev/staff)
--   public.fn_web_inquiries(p_from,p_to,p_q,p_kind,p_status,p_handler,p_limit,p_offset) → rows(연락처 마스킹)+summary+handlers+months
-- v59 화면 : 문의 관리에 '홈페이지 문의' 카드 (요약·필터·표·[붙여넣기로 등록] — 고도몰 목록을 그대로 붙여 넣음, 앞뒤 빈 칸·[관리] 열 허용)
--            카드 안 .filters 를 공통 바(.cbar)와 같은 모양·왼쪽 정렬로 통일. 담당자 상담 입력 관심 품목 여러 개 선택(쉼표로 저장).
-- v60 화면 : 상담 입력 관심 모델도 여러 개(Enter·쉼표로 칩 추가, 쉼표로 저장) · 가져오기 이카운트 가망고객에 '관심 품목코드'→interest_model_code 매핑 추가
-- mvp_109·110 (2026-09-07) 일 마감 = 판매 입력의 확인 단계
--   core.store_daily 는 (구분·프로) 줄이 진실. sales=판매완료(확정) · pending_sales=매출(미확정, 집계엔 안 씀) · src_count=그날 판매 입력 건수
--   fn_store_daily_prefill(p_code,p_date,p_store,p_all) : 그날 판매 입력을 구분·프로별로 집계(판매완료/매출 따로) + 저장된 마감 + DPS 합계. p_all=false 면 내 줄만
--   fn_store_daily_submit : 프로 없는 줄은 받지 않음. 프로별 줄을 넣으면 같은 날·구분의 handler='' (시트 매장합계) 줄은 지움(이중 집계 방지). 안 보낸 줄 삭제는 내가 넣은 줄만
--   core.store_daily_dps + fn_store_dps_submit : DPS 일시불·구독 합계는 대사용으로 따로 (매출 집계엔 프로별 마감이 쓰임)
--   fn_store_daily_delete(p_code,p_date,p_store,p_all) : 기본은 내 줄(+시트 줄)만, p_all 이면 그 날 전부
--   fn_store_status : unclosed_mine(내 판매 입력이 있는데 내 마감 없는 날) · closed_mine 추가. unclosed_days/closed_recent 는 매장 전체(+by)
--   fn_store_requests : by_dept(요청자 부서) 추가
-- v61 화면 : 담당자 일 마감 탭 재구성 — [본인|전체] 토글(기본 본인). 날짜 고르면 판매 입력이 구분·프로·판매완료/매출/환불 표로 자동 채워짐,
--            저장된 마감이 있으면 그 값·판매 입력과의 차이 표시. 전체 모드에서만 DPS 합계 대사 카드. 최근 마감·미마감도 본인/전체 따라감.
--            '매장 판매 요청' → '판매 요청' (요청자 이름 옆 부서), 카드 설명에 버튼 뜻.
-- mvp_111 (2026-09-07) 구독 상품 마스터 sub.plan (biz·cat1·cat2·term_years·model_code·cycle_months·care_case·total_fee·monthly_fee, 유니크 = 모델·기간·주기·케어)
--   + sub.plan_item (name·item_code·round_no). core.f_sub_plan_upsert(p_rows): '제품' 줄이 플랜, 뒤따르는 같은 키 줄이 구성. fn_sub_plan_upsert(admin/dev) · fn_sub_plans(p_q)
--   fn_store_sub_quote(p_code,p_model) : 담당자 상담 입력에서 모델 칩 넣으면 요금·주기·방문케어 횟수 참고 표시
-- v62 화면 : 관리자 품목 화면 '구독 상품 · 요금' 카드(붙여넣기 등록 — 엑셀 10열 그대로) · 담당자 상담 입력 관심 모델 아래 구독 요금 참고
-- mvp_112 (2026-09-07) 가망고객에 구매 제품 + 다음 구매 관심 : crm.consult.next_category/next_model_code/next_expected_date/next_note (purchase_item 은 기존 컬럼)
--   fn_store_consult_submit : purchase_item·next_* 저장
--   fn_store_sale_submit : 상담번호 연결 시 그 상담에 purchase_item(판매 상품명)·next_* 채움. next_model_code/next_category 가 있으면
--                          새 가망고객(source_ref SC…, 유입 '매장 구매 후', 관심=다음 제품, 진행중, linked_order_id=이번 판매) 을 이어 만든다
--   fn_consult_list : next_* 컬럼 추가(반환 타입 변경 → drop 후 재생성) · fn_store_status.my_open_consults : bought/next_model/next_cat/next_date
-- v63 화면 : 담당자 상담 입력 '구매 제품 · 다음 구매 관심' 상자, 판매 입력 '다음 구매 관심' 상자, 홈 진행중 상담에 "구매 X · 다음 Y (예정)" 줄, 관리자 상담 목록 관심 열에 구매/다음 표시
